// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task1.Models;

namespace task1.Migrations
{
    [DbContext(typeof(CountryContext))]
    [Migration("20211014210923_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("task1.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Capital")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numberpeople")
                        .HasColumnType("TEXT");

                    b.Property<string>("Territory")
                        .HasColumnType("TEXT");

                    b.Property<string>("VVP")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countriess");
                });
#pragma warning restore 612, 618
        }
    }
}
